# Generated by Django 2.2.11 on 2020-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200325_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='topTracks',
            field=models.CharField(max_length=50),
        ),
    ]
