# Generated by Django 3.0.4 on 2020-03-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200325_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artist',
            name='imageLink',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='artist',
            name='topTracks',
            field=models.CharField(max_length=150),
        ),
    ]
