# Generated by Django 3.0.4 on 2020-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200326_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yelpID', models.CharField(max_length=25)),
                ('imageURL', models.CharField(max_length=100)),
                ('yelpURL', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('reviewCount', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('location', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=4)),
            ],
        ),
    ]
