# Generated by Django 3.0.4 on 2020-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200326_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='imageLink',
            field=models.CharField(max_length=110),
        ),
    ]
