# Generated by Django 3.0.4 on 2020-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200327_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotifyLink',
            field=models.CharField(max_length=200),
        ),
    ]
