# Generated by Django 3.0.4 on 2020-03-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200327_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='track1popularity',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='track2popularity',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='track3popularity',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
