# Generated by Django 3.0.4 on 2020-03-29 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200328_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('concertName', models.CharField(max_length=200)),
                ('artists', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=80)),
                ('venue', models.CharField(max_length=200)),
                ('venueWebsite', models.CharField(max_length=200)),
                ('startingTime', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
