# Generated by Django 2.2.11 on 2020-03-29 03:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200328_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concertName', models.CharField(max_length=100)),
                ('artists', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=8)),
                ('city', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('venueWebsite', models.CharField(max_length=50)),
                ('startingTime', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
