# Generated by Django 2.2.11 on 2020-03-29 04:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_concerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerts',
            name='artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=80),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='concertName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='startingTime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='venue',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='venueWebsite',
            field=models.CharField(max_length=200),
        ),
    ]
