# Generated by Django 3.0.4 on 2020-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200329_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='upcomingConcert',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
