# Generated by Django 2.2.11 on 2020-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_concerts_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerts',
            name='imageURL',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
