# Generated by Django 3.0.4 on 2020-03-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_concerts_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='upcomingConcert',
            field=models.CharField(default='No Upcoming Concerts', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='upcomingConcert',
            field=models.CharField(default='No Upcoming Concerts', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotifyID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track1',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track2',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track3',
            field=models.CharField(max_length=105),
        ),
    ]
