# Generated by Django 3.0.4 on 2020-03-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20200329_1521'),
        ('webapp', '0017_concerts_imageurl'),
    ]

    operations = [
    ]
