# Generated by Django 3.0.4 on 2020-03-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200330_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='upcomingConcert',
            field=models.CharField(max_length=205),
        ),
    ]
