# Generated by Django 3.0.4 on 2020-03-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_merge_20200329_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerts',
            name='headliner',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='concerts',
            name='imageURL',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotifyID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track3',
            field=models.CharField(max_length=100),
        ),
    ]
