# Generated by Django 3.0.4 on 2020-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20200329_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track1',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track2',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track3',
            field=models.CharField(max_length=105),
        ),
    ]
