# Generated by Django 3.0.4 on 2020-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20200329_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=200),
        ),
    ]
