# Generated by Django 3.0.4 on 2020-03-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_venue_upcomingconcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='upcomingConcert',
            field=models.CharField(default='NO UPCOMING CONCERTS', max_length=205),
            preserve_default=False,
        ),
    ]
