# Generated by Django 3.0.4 on 2020-03-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200329_1754'),
        ('webapp', '0021_venue_upcomingconcert'),
        ('webapp', '0018_auto_20200329_1956'),
    ]

    operations = [
    ]
