# Generated by Django 3.0.4 on 2020-03-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20200329_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='upcomingConcert',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
