# Generated by Django 3.0.4 on 2020-03-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20200330_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='reviewCount',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='upcomingConcert',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='yelpURL',
        ),
    ]
