# Generated by Django 3.0.4 on 2020-03-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_artist_upcomingconcert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='upcomingConcert',
        ),
    ]
