# Generated by Django 3.0.4 on 2020-03-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_artist_upcomingconcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='upcomingConcert',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
