# Generated by Django 3.0.4 on 2020-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20200330_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='upcomingConcerts',
            field=models.CharField(default='NO CONCERT EXISTS HERE', max_length=200),
            preserve_default=False,
        ),
    ]
