# Generated by Django 3.0.4 on 2020-03-30 05:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_venue_upcomingconcerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='upcomingConcerts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=80),
        ),
    ]
