# Generated by Django 3.0.4 on 2020-03-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20200330_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='imageURL',
            field=models.CharField(default='Insert Image', max_length=300),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=30.2885, max_digits=17),
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default='Insert Location', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=97.7355, max_digits=17),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.CharField(default='$$', max_length=4),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='venue',
            name='reviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='yelpURL',
            field=models.CharField(default='Insert Yelp URL', max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(default='Insert Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='yelpID',
            field=models.CharField(default='Insert yelpID', max_length=25),
        ),
    ]
