# Generated by Django 3.0.4 on 2020-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20200330_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerts',
            name='yelpID',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='upcomingConcert',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
